version: '2'
services:
  schemaformapplication-app:
    image: schemaformapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://schemaformapplication-postgresql:5432/SchemaFormApplication
      - JHIPSTER_CACHE_REDIS_SERVER=redis://schemaformapplication-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://schemaformapplication-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  schemaformapplication-postgresql:
    extends:
      file: postgresql.yml
      service: schemaformapplication-postgresql
  schemaformapplication-redis:
    extends:
      file: redis.yml
      service: schemaformapplication-redis
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
